2022-03-13 14:38:23,053 ERROR: Exception on /reset_password_request [GET] [in c:\users\16496\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1458]
Traceback (most recent call last):
  File "c:\users\16496\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\16496\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\16496\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\16496\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\python\microblog\app\routes.py", line 128, in reset_password_request
    return render_template('reset_password_request.html', title='Reset Password', form=form)
  File "c:\users\16496\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\16496\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\16496\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "c:\users\16496\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "c:\users\16496\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "c:\users\16496\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "c:\users\16496\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\python\microblog\app\templates\reset_password_request.html", line 12, in template
    {{% endfor %}}
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
2022-03-13 14:38:41,082 ERROR: Exception on /reset_password_request [GET] [in c:\users\16496\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1458]
Traceback (most recent call last):
  File "c:\users\16496\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\16496\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\16496\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\16496\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\python\microblog\app\routes.py", line 128, in reset_password_request
    return render_template('reset_password_request.html', title='Reset Password', form=form)
  File "c:\users\16496\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\16496\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\16496\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "c:\users\16496\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "c:\users\16496\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "c:\users\16496\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "c:\users\16496\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\python\microblog\app\templates\reset_password_request.html", line 12, in template
    {{% endfor %}}
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
2022-03-13 14:39:49,836 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:48]
2022-03-13 14:43:53,120 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:48]
2022-03-13 14:43:55,890 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:48]
2022-03-13 14:45:41,975 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:48]
2022-03-13 14:47:18,074 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:48]
2022-03-13 14:48:12,627 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:48]
2022-03-13 14:54:50,621 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:48]
2022-03-13 15:07:11,586 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:48]
2022-03-13 15:07:35,526 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:48]
2022-03-13 15:11:07,757 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:48]
2022-03-13 15:14:59,036 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:48]
2022-03-13 15:15:09,074 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:48]
2022-03-13 15:18:42,964 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:48]
2022-03-13 15:19:35,079 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:43]
2022-03-13 15:19:37,608 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:43]
2022-03-13 15:20:58,234 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:43]
2022-03-13 15:21:01,592 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:43]
2022-03-13 15:21:04,421 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:43]
2022-03-13 15:21:16,875 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:43]
2022-03-13 15:28:19,173 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:43]
2022-03-13 15:28:50,761 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:43]
2022-03-13 15:31:29,476 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:43]
2022-03-13 15:31:32,057 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:43]
2022-03-13 15:32:33,997 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:42]
2022-03-13 15:48:25,349 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:42]
2022-03-13 15:55:39,875 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:42]
2022-03-13 15:58:33,067 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:42]
2022-03-13 15:58:57,957 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:42]
2022-03-13 15:59:54,635 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:42]
2022-03-13 16:01:37,250 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:44]
2022-03-13 16:06:15,181 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:43]
2022-03-13 16:06:56,289 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:43]
2022-03-13 16:07:48,429 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:43]
2022-03-13 16:35:50,396 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:44]
2022-03-13 17:00:04,233 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:45]
2022-03-13 17:00:06,826 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:45]
2022-03-13 17:12:56,225 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:45]
2022-03-13 17:12:58,751 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:45]
2022-03-13 17:44:31,681 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:47]
2022-03-13 17:44:34,785 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:47]
2022-03-13 18:12:40,649 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:55]
2022-03-13 18:12:43,813 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:55]
2022-03-13 18:15:39,696 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:55]
2022-03-13 18:16:28,239 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:55]
2022-03-13 18:16:56,901 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:55]
2022-03-13 18:19:43,086 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:55]
2022-03-13 18:20:07,060 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:55]
2022-03-13 18:20:54,489 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:55]
2022-03-13 18:21:17,818 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:55]
2022-03-13 18:21:25,697 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:55]
2022-03-13 18:22:25,140 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:55]
2022-03-13 18:22:53,668 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:55]
2022-03-15 19:13:27,751 INFO: Microblog startup [in D:\python\microblog\app\__init__.py:55]
